[variables]
NODE_VERSION = "18"

[phases.install]
cmds = [
  "cd shared && npm ci && npm run build",
  "cd backend && npm ci && npx prisma generate"
]

[phases.build]
cmds = [
  "cd backend && npm run build"
]

[phases.deploy]
cmds = [
  "cd backend && npx prisma migrate deploy"
]

[start]
cmd = "cd backend && npm start"
